# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'u2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys


import numpy as np

#pyside2 包的引入需再最前面，否则会报错
from PySide2.QtWidgets import QApplication,QMainWindow
from PySide2.QtUiTools import QUiLoader

class Ui_MainWindow(object):
    def __init__(self):
        self.ui = QUiLoader().load('u1.ui')

if __name__ == '__main__':
    app = QApplication(sys.argv)
    demo = Ui_MainWindow()
    demo.ui.show()
    sys.exit(app.exec_())